spring:
  application:
    name: template
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: ${RCALC_DB_USERNAME:root}
    password: ${RCALC_DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: myschema
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    placeholders:
      schema_name: myschema
  jpa:
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none