services:
  database:
    container_name: 'mydatabase'
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'